function result = gdFunction(Distro, x)
    diff = bsxfun(@minus, x, Distro.Rn);
    normValue = pdist2(Distro.Rn,x);
    
    if strcmp(Distro.type,'rayl')
        if strcmp(Distro.center,'mode')
            partialResult = sum(bsxfun(@times,...
                bsxfun(@rdivide,diff,normValue.^2),...
                (((Distro.Dn.^2)./(normValue).^2) - 2)));
        else %mean
            partialResult = sum(bsxfun(@times,...
                bsxfun(@rdivide,diff,normValue.^2),...
                (((Distro.Dn.^2)./(2*pi*normValue.^2)) - 2)));
        end
            
    end
    
    if strcmp(Distro.type,'maxB')
        if strcmp(Distro.center,'mode')
            partialResult = sum(bsxfun(@times,...
                bsxfun(@rdivide,diff,normValue.^2),...
                (((2.*Distro.Dn.^2)./(normValue.^2)) - 3)));
        else %mean
            partialResult = sum(bsxfun(@times,...
                bsxfun(@rdivide,diff,normValue.^2),...
                (((8.*Distro.Dn.^2)./(pi*normValue.^2)) - 3)));
        end
    end
    
    if strcmp(Distro.type,'expo')
        %Only computes the mean
        partialResult = sum(bsxfun(@times,...
            bsxfun(@rdivide,diff,normValue.^2),...
            ((Distro.Dn./normValue) - 1)));
            
    end
    
    if (strcmp(Distro.type,'gamm') & normValue > 0)    
        if strcmp(Distro.center,'mode')
            partialResult = sum(bsxfun(@times,...
                bsxfun(@rdivide,diff,normValue),...
                (2.*log(Distro.Dn).*normValue - ...
                Distro.Dn - 2.*normValue.*psi(normValue.^2+1) + ...
                normValue + 1./normValue - ...
                2.*normValue.*log(1./normValue))));
        else %mean
            partialResult = sum(bsxfun(@times,...
                bsxfun(@rdivide,diff,normValue),...
                (2.*log(Distro.Dn).*normValue - ...
                Distro.Dn - 2.*normValue.*psi(normValue.^2) + ...
                normValue - 2.*normValue.*log(1./normValue))));
        end
            
    end
    
    if strcmp(Distro.type,'igam')
        if (strcmp(Distro.center,'mode') & normValue > 1)    
            partialResult = sum(bsxfun(@times,...
                bsxfun(@rdivide,diff,normValue),...
                (log(normValue.^2) + 2 - ...
                bsxfun(@rdivide,2.*normValue,Distro.Dn) - ...
                log(Distro.Dn) - 2./normValue - psi(normValue - 1))));
        else %mean
            partialResult = sum(bsxfun(@times,...
                bsxfun(@rdivide,diff,normValue),...
                (log(normValue.^2) + 2 - ...
                bsxfun(@rdivide,2.*normValue,Distro.Dn) - ...
                log(Distro.Dn) + 2./normValue - psi(normValue + 1))));
        end
            
    end
    
    if strcmp(Distro.type,'unif')
        %Only computes the mean
        partialResult = -sum(bsxfun(@rdivide,diff,normValue.^2));
    end
    

    result = partialResult - (Distro.Sigma\(x-Distro.r_mean)')';
end
